---
- hosts: logstash

  tasks:
  - name: Stop Nginx
    service: name=nginx state=stopped
    become: yes
	
  - name: Download Build File
    shell: "aws s3 cp s3://jenkinstest-rahul/builds/jobs/MLCOITest/5/index.html /home/ec2-user/5/"